<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentHtml\FluentHtml.csproj" />
    <ProjectReference Include="..\FluentHtml.Http\FluentHtml.Http.csproj" />
    <ProjectReference Include="..\FluentHtml.Htmx\FluentHtml.Htmx.csproj" />
    <ProjectReference Include="..\FluentHtml.Bootstrap\FluentHtml.Bootstrap.csproj" />
    <ProjectReference Include="..\FluentHtml.Forms\FluentHtml.Forms.csproj" />
    <ProjectReference Include="..\FluentHtml.Validation\FluentHtml.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
