<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentHtml\FluentHtml.csproj" />
    <ProjectReference Include="..\FluentHtml.Http\FluentHtml.Http.csproj" />
    <ProjectReference Include="..\FluentHtml.Htmx\FluentHtml.Htmx.csproj" />
    <ProjectReference Include="..\FluentHtml.Bootstrap\FluentHtml.Bootstrap.csproj" />
    <ProjectReference Include="..\FluentHtml.Forms\FluentHtml.Forms.csproj" />
    <ProjectReference Include="..\FluentHtml.Validation\FluentHtml.Validation.csproj" />
  </ItemGroup>

</Project>
