global using FluentHtml.Bootstrap.Components;
global using FluentHtml.Elements;
global using FluentHtml.AspNetCore;
global using FluentHtml.Htmx;
global using FluentHtml.Nodes;
global using FluentHtml.Rendering;
global using FluentHtml.Forms;
global using FluentHtml.Validation;
global using Microsoft.AspNetCore.Mvc;
global using FluentHtml.Samples.Pages;

global using static FluentHtml.Elements.DivExtensions;
global using static FluentHtml.Elements.Heading1Extensions;
global using static FluentHtml.Elements.Heading2Extensions;
global using static FluentHtml.Elements.Heading3Extensions;
global using static FluentHtml.Elements.Heading4Extensions;
global using static FluentHtml.Elements.ParagraphExtensions;
global using static FluentHtml.Elements.AnchorExtensions;
global using static FluentHtml.Elements.NavExtensions;
global using static FluentHtml.Elements.TableExtensions;
global using static FluentHtml.Elements.FormExtensions;
global using static FluentHtml.Elements.InputExtensions;
global using static FluentHtml.Elements.LabelExtensions;
global using static FluentHtml.Elements.SelectExtensions;
global using static FluentHtml.Elements.ScriptExtensions;
global using static FluentHtml.Elements.LinkExtensions;
global using static FluentHtml.Elements.MetaExtensions;
global using static FluentHtml.Elements.OptionExtensions;
global using static FluentHtml.Elements.StrongExtensions;
global using static FluentHtml.Elements.CodeExtensions;
global using static FluentHtml.Elements.TextareaExtensions;
global using static FluentHtml.Elements.BlockquoteExtensions;
global using static FluentHtml.Elements.PreExtensions;
global using static FluentHtml.Elements.KbdExtensions;
global using static FluentHtml.Elements.MarkExtensions;
global using static FluentHtml.Elements.DetailsExtensions;
global using static FluentHtml.Elements.SummaryExtensions;
global using static FluentHtml.Elements.EmExtensions;
global using static FluentHtml.Elements.SmallExtensions;
global using static FluentHtml.Elements.HrExtensions;
global using static FluentHtml.Elements.SpanExtensions;

global using static FluentHtml.Bootstrap.Components.ButtonExtensions;
global using static FluentHtml.Bootstrap.Components.CardExtensions;
global using static FluentHtml.Bootstrap.Components.AlertExtensions;
global using static FluentHtml.Bootstrap.Components.BadgeExtensions;
global using static FluentHtml.Bootstrap.Components.NavbarExtensions;
global using static FluentHtml.Bootstrap.Components.ModalExtensions;
global using static FluentHtml.Bootstrap.Components.AccordionExtensions;
global using static FluentHtml.Bootstrap.Components.ToastExtensions;
global using static FluentHtml.Bootstrap.Components.DropdownExtensions;
global using static FluentHtml.Bootstrap.Components.PaginationExtensions;
global using static FluentHtml.Bootstrap.Components.BreadcrumbExtensions;
global using static FluentHtml.Bootstrap.Components.SpinnerExtensions;
