var builder = WebApplication.CreateBuilder(args);
builder.Services.AddAntiforgery();

var app = builder.Build();

app.UseAntiforgery();

var routes = app.FluentRouting();
routes.MapGet("/", HomePage.Render);
routes.MapGet("/core", CorePage.Render);
routes.MapGet("/htmx", HtmxPage.Render);
routes.MapGet("/htmx/table", HtmxPage.RenderTable);
routes.MapGet("/htmx/alert", HtmxPage.RenderAlert);
routes.MapGet("/htmx/alert/dismiss", HtmxPage.DismissAlert);
routes.MapGet("/bootstrap", BootstrapPage.Render);
routes.MapGet("/forms", FormsPage.Render);
routes.MapPost("/forms/create", FormsPage.CreateUser);
routes.MapGet("/todo", TodoPage.Render);
routes.MapPost("/todo/add", TodoPage.AddTodo);
routes.MapPatch("/todo/toggle/{id}", TodoPage.ToggleTodo);
routes.MapDelete("/todo/delete/{id}", TodoPage.DeleteTodo);
routes.MapGet("/dashboard", DashboardPage.Render);
routes.MapGet("/customers", CrudPage.Render);
routes.MapGet("/customers/table", CrudPage.RenderCustomerTable);
routes.MapPost("/customers/create", CrudPage.CreateCustomer);
routes.MapGet("/customers/edit/{id}", CrudPage.EditCustomer);
routes.MapGet("/customers/cancel/{id}", CrudPage.CancelEdit);
routes.MapPost("/customers/update/{id}", CrudPage.UpdateCustomer);
routes.MapDelete("/customers/delete/{id}", CrudPage.DeleteCustomer);
routes.MapGet("/markdown", MarkdownPage.Render);
routes.MapGet("/autoform", AutoFormPage.Render);
routes.MapPost("/autoform/create", AutoFormPage.CreateUser);
routes.MapGet("/datagrid", DataGridPage.Render);
routes.MapGet("/api/customers", DataGridPage.HandleApiRequest);
routes.MapGet("/charts", ChartsPage.Render);
routes.MapGet("/upload", UploadPage.Render);
routes.MapGet("/tabs", TabsPage.Render);
routes.MapGet("/layouts", LayoutsPage.Render);
routes.MapGet("/tree", TreePage.Render);
routes.MapGet("/tree/users", TreePage.LoadUsers);
routes.MapGet("/tree/products", TreePage.LoadProducts);
routes.MapGet("/tree/orders", TreePage.LoadOrders);
routes.MapGet("/feedback", FeedbackPage.Render);
routes.MapDelete("/feedback/confirm-delete", FeedbackPage.ConfirmDelete);
routes.MapGet("/feedback/toast/success", FeedbackPage.ToastSuccess);
routes.MapGet("/feedback/toast/error", FeedbackPage.ToastError);
routes.MapGet("/feedback/toast/warning", FeedbackPage.ToastWarning);
routes.MapGet("/feedback/toast/info", FeedbackPage.ToastInfo);
routes.MapGet("/wizard", WizardPage.Render);
routes.MapGet("/wizard/step/account", WizardPage.StepAccount);
routes.MapGet("/wizard/step/profile", WizardPage.StepProfile);
routes.MapGet("/wizard/step/review", WizardPage.StepReview);
routes.MapPost("/wizard/step/complete", WizardPage.StepComplete);

app.Run();
